{% set name = "edn_format" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9a9f22d3a8b35b51b2f06a3e84d6411ae0c750e947c64a4536989eb84de1c56

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - ply >=3.10
    - pyrfc3339 >=0.2
    - pytz >=2016.10

test:
  imports:
    - edn_format
  commands:
    - pip check

about:
  home: https://swaroopch.com/2012/12/24/edn-format-python/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: EDN reader and writer implementation in Python, using PLY (lex, yacc)

  description: |
    Implements the EDN format in Python. All features of EDN are 
    implemented, including custom tagged elements.
  doc_url: https://github.com/swaroopch/edn_format
  dev_url: https://github.com/swaroopch/edn_format

extra:
  recipe-maintainers:
    - jan-janssen
