{% set name = "edn_format" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05a4b3078def5e4bb07ed58fb48c2aef52f3db019489dc2845808a5ae990c80e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pip
    - ply >=3.10
    - pyrfc3339 >=0.2
    - pytz >=2016.10

test:
  requires:
    - python {{ python_min }}
  imports:
    - edn_format
  commands:
    - pip check

about:
  home: https://swaroopch.com/2012/12/24/edn-format-python/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: EDN reader and writer implementation in Python, using PLY (lex, yacc)

  description: |
    Implements the EDN format in Python. All features of EDN are 
    implemented, including custom tagged elements.
  doc_url: https://github.com/swaroopch/edn_format
  dev_url: https://github.com/swaroopch/edn_format

extra:
  recipe-maintainers:
    - jan-janssen
